# Generated by Django 5.0.2 on 2024-02-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=105)),
                ('cover', models.TextField()),
                ('category', models.CharField(max_length=150)),
                ('url', models.URLField()),
            ],
        ),
    ]
