# Generated by Django 5.0.2 on 2024-02-15 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albummodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='musicmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False),
        ),
    ]
