# Generated by Django 5.0.2 on 2024-02-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_counter', models.IntegerField()),
                ('music_in_each_category', models.CharField(max_length=255)),
                ('category_counter', models.CharField(max_length=255)),
            ],
        ),
    ]
