# Generated by Django 5.0.2 on 2024-02-15 17:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('creat_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-update_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AlbumModel',
            fields=[
                ('id', models.AutoField(auto_created=True, default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('creat_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Album', to='music.categorymodel', verbose_name='categories')),
            ],
            options={
                'ordering': ['-update_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MusicModel',
            fields=[
                ('id', models.AutoField(auto_created=True, default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('creat_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=100, null=True, unique=True)),
                ('cover', models.ImageField(null=True, upload_to='media')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='musics', to='music.albummodel', verbose_name='albums')),
            ],
            options={
                'ordering': ['-update_time'],
                'abstract': False,
            },
        ),
    ]
