# Generated by Django 5.0.2 on 2024-02-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('cover', models.ImageField(upload_to='')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
    ]
