# Generated by Django 5.0.2 on 2024-02-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
