# Generated by Django 5.0.2 on 2024-02-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_alter_music_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='cover',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
