# Generated by Django 4.2.10 on 2024-02-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_add_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='cover',
            field=models.ImageField(upload_to='covers'),
        ),
    ]
