# Generated by Django 4.2.10 on 2024-02-14 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_alter_add_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
