# Generated by Django 5.0.2 on 2024-02-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
